<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="PdfPig" Version="0.1.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LittleCheerful.Contracts\LittleCheerful.Contracts.csproj" />
  </ItemGroup>

</Project>
